version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8000:8000"
    environment:
      - FLASK_APP=web_app.py
      - FLASK_ENV=development
      - API_BASE_URL=http://api:5000/api/v1
      - PORT=8000
    depends_on:
      - api
    volumes:
      - ./templates:/app/templates
      - ./static:/app/static
    networks:
      - skyquest-network
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=enhanced_app.py
      - FLASK_ENV=development
      - PORT=5000
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    networks:
      - skyquest-network
    restart: unless-stopped

networks:
  skyquest-network:
    driver: bridge 